name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ fromJSON('{"go": "1.16"}') }} # Replace with dynamic extraction from go.mod

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v1

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Bazel build artifacts
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/MODULE.bazel.lock') }}

      - name: Build with Bazel
        run: bazel build //...

      - name: Test with Bazel
        run: bazel test //...
