name: Nightly Trunk Upgrade Workflow

permissions: read-all

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Use the latest stable version of checkout

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1 # Use the latest stable version of trunk-action
