name: PR

permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Cache Bazel
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE','MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: |
          bazelisk run //:gazelle-update-repos-go
          bazelisk run //:gazelle
          bazelisk build //...

      # - name: Unit Tests
      #   run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --coverprofile=cover.json --race --trace --json-report=report.json --timeout=10m -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -tags=unit_tests

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: unit-tests
      #     files: ./cover.json,./report.json
      #     fail_ci_if_error: true
      #     verbose: true

  compute_impacted_targets:
    uses: dragonfish/workflows/.github/workflows/compute-impacted-targets.yaml@main
    secrets: inherit

  auto_merge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto Merge PR if bot
    uses: dragonfish/workflows/.github/workflows/auto-merge.yaml@main
